name: PR Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

env:
  PYTHON_VERSION: 3.11

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Python ${{ env.PYTHON_VERSION }}
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}
  #     - name: Display Python version
  #       run: python -c "import sys; print(sys.version)"
  #     - name: Install linter
  #       run: pip install pylint
  #     - name: Lint
  #       run: pylint *.py **/*.py

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backend:$(date +%s)
