name: PR Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.11.5-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install linter
        run: pip install pylint
      - name: Lint
        run: pylint *.py **/*.py

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test-backend-image:$(date +%s)
